name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          branch: main
      - uses: retypeapp/action-build@latest
        with:
          branch: main

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
          branch: main
